src/main/java/edu/iit/sat/itmd4515/gsambasivan/web/AddProductController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.gsambasivan.web;

import edu.iit.sat.itmd4515.gsambasivan.domain.Product;
import edu.iit.sat.itmd4515.gsambasivan.domain.ProductCategory;
import edu.iit.sat.itmd4515.gsambasivan.domain.SubCategory;
import edu.iit.sat.itmd4515.gsambasivan.ejb.ProductCategoryService;
import edu.iit.sat.itmd4515.gsambasivan.ejb.ProductService;
import edu.iit.sat.itmd4515.gsambasivan.ejb.SubCategoryService;
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import org.primefaces.context.RequestContext;

/**
 *
 * @author Swathi
 */

@ManagedBean
@ViewScoped
public class AddProductController implements Serializable {
      @EJB
    private SubCategoryService subCategoryService;
   @EJB
    private ProductCategoryService productCategoryService;
    @EJB
    private ProductService productService;
    private String productCategory;
  
  
    private String subCategory;
    
   private Map<String,Map<String,String>> data = new HashMap<String, Map<String,String>>();

    public Map<String, Map<String, String>> getData() {
        return data;
    }

    public void setData(Map<String, Map<String, String>> data) {
        this.data = data;
    }
    
    private Map<String,String> productCategories; 
    
       private Map<String,String> subCategories; 

    public String getProductCategory() {
        return productCategory;
    }

    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }

    public String getSubCategory() {
        return subCategory;
    }

    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }

    

    public Map<String, String> getProductCategories() {
        return productCategories;
    }

    public void setProductCategories(Map<String, String> productCategories) {
        this.productCategories = productCategories;
    }

    public Map<String, String> getSubCategories() {
        return subCategories;
    }

    public void setSubCategories(Map<String, String> subCategories) {
        this.subCategories = subCategories;
    }
    /**
     * Initializing product category dropdown for add product button
     */
    @PostConstruct
    public void init() {
    productCategories = new HashMap<String, String>();
        for(ProductCategory proCat :productCategoryService.findAll()){
            productCategories.put(proCat.getCategoryName(),proCat.getCategoryName());
    }
        
    }
    /**
     * Initializing product sub-category dropdown for add product button
     */
    public void onProductCategoryChange(){
   Map<String,String> map = new HashMap<String, String>();
       for(SubCategory cat :subCategoryService.findSubCategoryNames(getProductCategory())){
            
            map.put(cat.getCategoryName(),cat.getCategoryName());
       }
         data.put(getProductCategory(), map);
         if(productCategory !=null && !productCategory.equals(""))
         {
             subCategories = data.get(productCategory);
          
         } // subCategories = data.get(productCategory);
        else
            subCategories = new HashMap<String, String>();
   
      
    }
   
     /**
      * Will persist the new product to the database
      * @param name
      * @param price
      * @param qty
      * @return 
      */
   
    public String addNewProduct(String name, String price, String qty){
    Product product = new Product();
      
        
        ProductCategory p = productCategoryService.findByName(getProductCategory());
        SubCategory s = subCategoryService.findByName(getSubCategory());
       product.setProductName(name);
       product.setPrice(Double.parseDouble(price));
       product.setQty(Integer.parseInt(qty));
      product.setSubCategory(s);
       product.setProductCategory(p);
       
       productService.create(product);
      
       return "/admin/welcome.xhtml?faces-redirect=true";
    }
}

src/main/java/edu/iit/sat/itmd4515/gsambasivan/web/EditProductController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.gsambasivan.web;

import edu.iit.sat.itmd4515.gsambasivan.domain.Product;
import edu.iit.sat.itmd4515.gsambasivan.domain.ProductCategory;
import edu.iit.sat.itmd4515.gsambasivan.domain.SubCategory;
import edu.iit.sat.itmd4515.gsambasivan.ejb.ProductService;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Swathi
 */
@ManagedBean
@ViewScoped
public class EditProductController {
    private long productId;
@EJB
    private ProductService productService;
    
    private String editName;
    private int editQty;
    private double editPrice;
    private ProductCategory productCategory;
    private SubCategory subCategory;

    public ProductCategory getProductCategory() {
        return productCategory;
    }

    public void setProductCategory(ProductCategory productCategory) {
        this.productCategory = productCategory;
    }

    public SubCategory getSubCategory() {
        return subCategory;
    }

    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    
   private Product p;
    public String getEditName() {
        return editName;
    }

    public void setEditName(String editName) {
        this.editName = editName;
    }

    public int getEditQty() {
        return editQty;
    }

    public void setEditQty(int editQty) {
        this.editQty = editQty;
    }

    public double getEditPrice() {
        return editPrice;
    }

    public void setEditPrice(double editPrice) {
        this.editPrice = editPrice;
    }
    
    public long getProductId() {
        return productId;
    }

    public void setProductId(long productId) {
        this.productId = productId;
    }
    /**
     * For edit setting old values in textbox
     * Getting details of the table row by passing through parameter
     */
    @PostConstruct
    public void init() {
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        long selectedEntityId = Long.parseLong(params.get("productSel"));

        p = productService.findById(selectedEntityId);
        setEditName(p.getProductName());
        setEditPrice(p.getPrice());
        setEditQty(p.getQty());
        setProductCategory(p.getProductCategory());
        setSubCategory(p.getSubCategory());
    }
    /**
     * Edits are saved to database on save click
     */
    public void saveChanges(){
       
          p.setProductId(getProductId());
          p.setPrice(getEditPrice());
          p.setQty(getEditQty());
          p.setProductName(getEditName());
          productService.update(p);
          
    }
}

src/main/java/edu/iit/sat/itmd4515/gsambasivan/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.gsambasivan.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;

/**
 *
 * @author Swathi
 */
@Named
@RequestScoped
public class LoginController extends BaseController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    @NotNull(message = "You must enter a username.")
    private String username;
    @NotNull(message = "You must enter a password.")
    private String password;

    public LoginController() {
    }

    // utility methods
    public String getRemoteUser() {
        return context.getExternalContext().getRemoteUser();
    }

    public boolean isAdmin() {
        return context.getExternalContext().isUserInRole("ADMIN_ROLE");
    }

    public boolean isCustomer() {
        return context.getExternalContext().isUserInRole("CUSTOMER_ROLE");
    }

    // action methods
    public String doLogin() {
        HttpServletRequest req = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            req.login(username, password);
        } catch (ServletException ex) {
            // login failed, first log the message
            LOG.log(Level.SEVERE, null, ex);
            // provide useful message to user - NOT the actual exception
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed Login", "Username and/or Password was not valid."));
            // short circuit the navigation and send back to login page with message
            return "/login.xhtml";
        }
        if(isAdmin()){
            return "/admin/welcome.xhtml";
        }
        return "/customer/welcome.xhtml";
    }
/**
 * 
 * @return  appropriate url to redirect to login page
 */
    public String doLogout() {
        HttpServletRequest req = (HttpServletRequest) context.getExternalContext().getRequest();
        System.out.println("Logging out");
        try {
            
            req.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed Logout", ""));
            return "/login.xhtml";
        }
        
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "You have logged out", "You have logged out successfully.  Please don't forget to close your browser."));
        return "/login.xhtml";
    }

    /**
     * Get the value of username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the value of username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Get the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

}

src/main/webapp/admin/addProduct.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Add Product</title>
    </h:head>
    <h:body>
        <h:form>
          <p:growl id="growl" life="2000" />
    <h:panelGrid columns="2" cellpadding="5">
         <p:outputLabel value="Product Category: " />
         <p:selectOneMenu id="productCategory" value="#{addProductController.productCategory}" style="width:150px">
              <p:ajax listener="#{addProductController.onProductCategoryChange}" update="subCategory" />
                <f:selectItem itemLabel="Select Product Category" itemValue="" noSelectionOption="true" />
                <f:selectItems value="#{addProductController.productCategories}" />
            </p:selectOneMenu>
         
          <p:outputLabel for="subCategory" value="Sub Category: " />
          <p:selectOneMenu id="subCategory" value="#{addProductController.subCategory}" style="width:150px">
              
                <f:selectItem itemLabel="Select SubCategory" itemValue="addProductController.subCategory"  />
                <f:selectItems value="#{addProductController.subCategories}" />
 
            </p:selectOneMenu>
        <p:outputLabel  value="Product Name" />
        <p:inputText binding="#{productName}"  />
 
        <p:outputLabel  value="Price" />
        <p:inputText binding="#{price}" />
        
         <p:outputLabel  value="Quantity" />
        <p:inputText binding="#{quantity}" />
        
        <p:commandButton value="Add" id="add" update="growl"  actionListener="#{addProductController.addNewProduct(productName.value, price.value, quantity.value)}" action="/admin/welcome" styleClass="ui-priority-primary">
         
        </p:commandButton>
    </h:panelGrid>
          
     </h:form>
    </h:body>
</html>

src/main/webapp/admin/addProductCategory.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Add Product Category</title>
    </h:head>
    <h:body>
     <h:form>
         <p:growl id="growl" life="2000" />
    <h:panelGrid columns="2" cellpadding="5">
        <p:outputLabel  value="Product Category " />
        <p:inputText binding="#{productCatName}"  />
 
        <p:outputLabel  value="Description:" />
        <p:inputText binding="#{productCatDesc}" />
        
        <p:commandButton value="Add" id="add" update="growl" actionListener="#{productCategoryController.addProductCategory(productCatName.value,productCatDesc.value)}" styleClass="ui-priority-primary" />
    </h:panelGrid>
     </h:form>
    </h:body>
</html>

src/main/webapp/admin/addSubCategory.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
          
    <h:head>
        <title>Add Sub Category</title>
    </h:head>
    <h:body>
        <h:form>
         
    <h:panelGrid columns="2" cellpadding="5">
         <p:outputLabel value="Product Category: " />
         <p:selectOneMenu id="productCategory" value="#{subCategoryController.productCategory}" style="width:150px">
              
                <f:selectItem itemLabel="Select Product Category" itemValue="" noSelectionOption="true" />
                <f:selectItems value="#{subCategoryController.productCategories}" />
            </p:selectOneMenu>
        <p:outputLabel  value="Sub Product Category " />
        <p:inputText binding="#{productCatName}"  />
 
        <p:outputLabel  value="Description:" />
        <p:inputText binding="#{productCatDesc}" />
        
        <p:commandButton value="Add" id="add"  actionListener="#{subCategoryController.addSubCategory(productCatName.value,productCatDesc.value)}" styleClass="ui-priority-primary" />
    </h:panelGrid>
     </h:form>
    </h:body>
</html>

src/main/webapp/admin/editProduct.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      template="./../WEB-INF/templates/authnTemplate.xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
     <ui:define name="title">
        Edit Product
     </ui:define>
    
    <ui:define name="content">
        <h:form>
        <p:panelGrid>
        <p:outputLabel  value="Product Name" />
        <p:inputText  value="#{editProductController.editName}"  />
 
        <p:outputLabel  value="Price" />
        <p:inputText value="#{editProductController.editPrice}" />
        
         <p:outputLabel  value="Quantity" />
         <p:inputText value="#{editProductController.editQty}" />
        
         <p:commandButton value="Edit" id="edit"   actionListener="#{editProductController.saveChanges()}" action="/admin/welcome" styleClass="ui-priority-primary" >
             
         </p:commandButton>
    </p:panelGrid>
          
     </h:form>
    <f:metadata>
    <f:viewParam name="productSel" value="#{editProductController.productId}"  />
</f:metadata>
       
    </ui:define>
</ui:composition>

src/main/webapp/admin/mail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Send mail to customer</title>
    </h:head>
    <h:body>
        <h:form>
            <p:panel class="panel panel-primary">
            
            <h:panelGrid columns="2" class="panel-body" cellpadding="5">
             
                <p:outputLabel value="Customer Name"/>
                <p:inputText value="#{mail.name}"/>
                <p:outputLabel value="Subject"/>
                <p:inputText value="#{mail.header}"/>
                <p:outputLabel value="Email"/>
                <p:inputText value="#{mail.emailAddr}"/>
                <p:outputLabel value="Message" />
                <p:inputTextarea rows="6" cols="33" value="#{mail.body}" />
                <p:commandButton actionListener="#{mail.sendMail()}" value="Send" action="welcome.xhtml" />
               
            </h:panelGrid>
            </p:panel>
        </h:form>
    </h:body>
</html>

src/main/webapp/admin/profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      template="./../WEB-INF/templates/authnTemplate.xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
   
    <ui:define name="title">
        Admin Profile
    </ui:define>
    <ui:define name="content">
         <h:dataTable class="table table-striped table-hover" value="#{adminService.findByUsername(loginController.remoteUser)}" var="admin">
            <h:column>
                <f:facet name="header">
                    <h:outputText value="ID"/>
                </f:facet>
                <h:outputText value="#{admin.personId}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="First Name"/>
                </f:facet>
                <h:outputText value="#{admin.firstName}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Last Name"/>
                </f:facet>
                <h:outputText value="#{admin.lastName}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Email ID"/>
                </f:facet>
                <h:outputText value="#{admin.email}"/>
            </h:column>
             <h:column>
                <f:facet name="header">
                    <h:outputText value="Contact No."/>
                </f:facet>
                <h:outputText value="#{admin.designation}"/>
            </h:column>   
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Store Location"/>
                </f:facet>
                <h:outputText value="#{admin.storeLocation}"/>
            </h:column>  

        </h:dataTable>
    
    </ui:define>
       
</ui:composition>

src/main/webapp/admin/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authnTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">
        Admin Welcome
    </ui:define>

    <ui:define name="content">
        Hello Admin #{loginController.remoteUser}
    <h:form>
   
 
    <p:commandButton value="Add Product Category" icon="ui-icon-extlink" actionListener="#{productCategoryController.addProductCategoryDialog()}">
       <!-- <p:ajax event="dialogReturn" listener="#{dfView.onCarChosen}" update="growl" />-->
    </p:commandButton>
        
        <p:commandButton value="Add Sub Product Category" icon="ui-icon-extlink" actionListener="#{subCategoryController.addProductCategoryDialog()}">
       <!-- <p:ajax event="dialogReturn" listener="#{dfView.onCarChosen}" update="growl" />-->
    </p:commandButton>
         
        <p:commandButton value="Add Product" icon="ui-icon-extlink" action="/admin/addProduct">
       
    </p:commandButton>
 
        
        <p:commandButton value="Send Email to customer" icon="ui-icon-extlink" actionListener="#{mail.openDialog()}">
       <!-- <p:ajax event="dialogReturn" listener="#{dfView.onCarChosen}" update="growl" />-->
    </p:commandButton>
    </h:form>
        <h:form id="tableForm">
            <p:dataTable id="productTable" class="table table-striped table-hover" value="#{productController.pr}" var="product"
                 paginator="true" rows="10"
                 paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                 rowsPerPageTemplate="5,10,15" selectionMode="single" selection="#{productController.selectedProduct}"   lazy="true"
                 emptyMessage="No products found!!" 
                 >
                        
            
           <p:column headerText="Product Category" sortBy="#{product.productCategory.categoryName}" filterBy="#{product.productCategory.categoryName}">                
               <h:outputText value="#{product.productCategory.categoryName}"/>
            </p:column>
             <p:column headerText="Product SubCategory" sortBy="#{product.subCategory.categoryName}" filterBy="#{product.subCategory.categoryName}">
              
                 <h:outputText value="#{product.subCategory.categoryName}"/>
            </p:column>
             <p:column headerText="Product" sortBy="#{product.productName}" filterBy="#{product.productName}">
               
                 <h:outputText value="#{product.productName}"/>
            </p:column>
            <p:column headerText="Price" sortBy="#{product.price}" filterBy="#{product.price}" >
                
                 <h:outputText value="#{product.price}"/>
            </p:column>
            <p:column headerText="Quantity" sortBy="#{product.qty}" filterBy="#{product.qty}">
                
                 <h:outputText value="#{product.qty}"/>
            </p:column>
            <p:column>
                <p:link outcome="/admin/editProduct" value="Edit" >
                <f:param name="productSel" value="#{product.productId}" />
            </p:link>
               
            </p:column>
            <p:column>
                 <p:growl id="message" showDetail="true" />
 
    <p:commandButton value="Delete" actionListener="#{productController.deleteProduct(product)}" >
        <p:confirm header="Confirmation" message="Are you sure?" icon="ui-icon-alert" />
        
    </p:commandButton>
 
    <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
        <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"  />
        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
    </p:confirmDialog>
            </p:column>
        </p:dataTable>
       
        </h:form>
    </ui:define>

</ui:composition>